SLIDE_PATH: '/Users/nam.le/Desktop/research/camil_pytorch/data_gdown/slide_paths' #replace you path 
JSON_PATH: '/Users/nam.le/Desktop/research/camil_pytorch/data_gdown/json_file' # replace your path https://drive.google.com/drive/folders/1U7xxQZPXrla2upVTMpubhZIiA9o7A2AO?fbclid=IwAR0gqG32lev8DoP8F4L68ou8uRLj_fqIsKzJCEgdYe-anZ5NPCaPvwBY54s
SPIXEL_PATH: '/Users/nam.le/Desktop/research/camil_pytorch/data_gdown/superpixels' # https://drive.google.com/drive/folders/1wss_cxh424pfmCAbOk1aDN1lbvC7x61p?fbclid=IwAR0gqG32lev8DoP8F4L68ou8uRLj_fqIsKzJCEgdYe-anZ5NPCaPvwBY54s
scoring_function: get_scoring_do_nothing 
pruning_function: get_pruning_do_nothing
batch_size: 256
